apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: bucket-info
deploy:
  kustomize:
    paths:
      - kubernetes-manifests/base
profiles:
  - name: local
    build:
      artifacts:
        - image: dev-workflow
          context: .
          buildpack:
            builder: "gcr.io/buildpacks/builder:v1"
      local:
        push: false
      tagPolicy:
        sha256: {}
    deploy:
      kubeContext: minikube
      kustomize:
        paths:
          - kubernetes-manifests/overlays/dev-local
  - name: remote
    build:
      artifacts:
        - image: us-central1-docker.pkg.dev/ejmadkins-path-to-production/web-app/leeroy-web
          context: .
          buildpack:
            builder: "gcr.io/buildpacks/builder:v1"
      tagPolicy:
        sha256: {}
      googleCloudBuild:
        projectId: ejmadkins-path-to-production
    deploy:
      kubeContext: gke_ejmadkins-path-to-production_europe-west2-a_dev
      kustomize:
        paths:
          - kubernetes-manifests/overlays/dev-remote
