apiVersion: skaffold/v3
kind: Config
metadata:
  name: bucket-info
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/ejmadkins-path-to-production/web-app/leeroy-web
      context: .
      buildpacks:
        builder: 'gcr.io/buildpacks/builder:v1'
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: true
  googleCloudBuild:
    projectId: ejmadkins-path-to-production
manifests:
  kustomize:
    paths:
      - kubernetes-manifests/ci
