apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: bucket-info
deploy:
  kustomize:
    paths:
      - kubernetes-manifests/base
profiles:
  - name: local
    build:
      artifacts:
        - image: dev-workflow
          context: .
          buildpack:
            builder: "gcr.io/buildpacks/builder:v1"
      local:
        push: false
      tagPolicy:
        sha256: {}
    deploy:
      kubeContext: minikube
      kustomize:
        paths:
          - kubernetes-manifests/overlays/dev-local
  - name: remote
    build:
      artifacts:
        - image: europe-west2-docker.pkg.dev/ejmadkins-cloud-workstations/workstations-demo/workstations/workstations-demo
          context: .
          buildpack:
            builder: "gcr.io/buildpacks/builder:v1"
      tagPolicy:
        sha256: {}
      googleCloudBuild:
        projectId: ejmadkins-cloud-workstations
    deploy:
      kubeContext: gke_ejmadkins-cloud-workstations_europe-west2-a_dev-cluster
      kustomize:
        paths:
          - kubernetes-manifests/overlays/dev-remote
