apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buckets-info
  name: buckets-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buckets-info
  template:
    metadata:
      labels:
        app: buckets-info
    spec:
      containers:
        - image: dev-workflow
          name: buckets-info
